name: Create Jira Issue from GitHub Issue

on:
  issues:
    types: [opened]

jobs:
  create-jira-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Jira Login
        uses: atlassian/gajira-login@v3
        with:
          site: ${{ secrets.JIRA_BASE_URL }}
          email: ${{ secrets.JIRA_USER_EMAIL }}
          api-token: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create Jira Issue
        id: create-issue
        uses: atlassian/gajira-create@v3
        with:
          project: KAN  # 프로젝트 키 확인 필요
          issuetype: Task
          summary: "${{ github.event.issue.title }}"
          description: |
            h3. GitHub Issue Link
            - [GitHub Issue](${{ github.event.issue.html_url }})
            
            h3. 상세 내용
            ${{ github.event.issue.body }}

      - name: Add Jira Issue Key as GitHub Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "${{ steps.create-issue.outputs.issue }}"

      - name: Comment on GitHub Issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "Jira Issue Created: [${{ steps.create-issue.outputs.issue }}](https://moodcanvas.atlassian.net/browse/${{ steps.create-issue.outputs.issue }})"
